# coding: utf-8

"""
    nexchange

    API for crypto currency exchange.

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import nexchange
from nexchange.rest import ApiException
from nexchange.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = nexchange.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_en_api_v1_currency_get(self):
        """
        Test case for en_api_v1_currency_get

        Get Currencies
        """
        pass

    def test_en_api_v1_orders_get(self):
        """
        Test case for en_api_v1_orders_get

        Get Orders
        """
        pass

    def test_en_api_v1_orders_post(self):
        """
        Test case for en_api_v1_orders_post

        Create Anonymous Order
        """
        pass

    def test_en_api_v1_orders_unique_reference_get(self):
        """
        Test case for en_api_v1_orders_unique_reference_get

        Get Order
        """
        pass

    def test_en_api_v1_pair_get(self):
        """
        Test case for en_api_v1_pair_get

        Get Pairs
        """
        pass

    def test_en_api_v1_price_pair_name_history_get(self):
        """
        Test case for en_api_v1_price_pair_name_history_get

        Get Ticker History
        """
        pass

    def test_en_api_v1_price_pair_name_latest_get(self):
        """
        Test case for en_api_v1_price_pair_name_latest_get

        Get Latest Ticker
        """
        pass

    def test_en_api_v1_users_me_orders_get(self):
        """
        Test case for en_api_v1_users_me_orders_get

        Get User Orders
        """
        pass

    def test_en_api_v1_users_me_orders_post(self):
        """
        Test case for en_api_v1_users_me_orders_post

        Create User Order
        """
        pass

    def test_en_api_v1_users_me_orders_unique_reference_get(self):
        """
        Test case for en_api_v1_users_me_orders_unique_reference_get

        Get User Order
        """
        pass


if __name__ == '__main__':
    unittest.main()
